### ISSUE TITLE
Ecomax 850I support

### ISSUE THREAD

**Issue by zASSAz** [denpamusic/PyPlumIO#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [X] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

I have Ecomax 850i3 standalone controller. It will be fine to have this controller supported. Can assist of getting required information for implementation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Thank you for your feedback and sorry for late response.

As far as I can tell from documentation, EM850i is supported by ecoNET300 device, so it should already work fine, albeit with limited functionality, as compared to connecting it to real EN300.

PyPlumIO is based on EN300 firmware, so any devices supported by EN300 should be supported by PyPlumIO without requiring any modification.

**Comment by denpamusic** [comment]
As of version 0.2.25 this library supports device specific parameters for ecoMAX i-series.
This includes both controller parameters and mixer (circuits in i-series) parameters.

If you're interested, you can see available controller parameters for ecoMAX 850i [here](https://github.com/denpamusic/PyPlumIO/blob/v0.2.25/pyplumio/structures/ecomax_parameters.py#L156) and mixer(circuits) parameters [here](https://github.com/denpamusic/PyPlumIO/blob/v0.2.25/pyplumio/structures/mixer_parameters.py#L28).

Names are taken from official ecoNET300 firmware.
I'll need to get myself an EM 850i manual, to better understand what they referring to😅

HASS integration using this version will release soon. I don't plan to add all available parameters for 850i to HASS, since it'll add unnecessary load on state machine and it's db. For parameters that you rarely change, it's better to use "Parameter set" service, that now also works with mixers(circuits). However, if you absolutely need access to some parameter through HASS UI, please feel free to contact me with a list of parameter names, that you want exposed to HASS.

Thanks again for providing diagnostic data for the controller!👍

**Comment by zASSAz** [comment]
Thank you for 850i implementation.
Can you please add sensors to 850I hass integration:
heating_target  >in HA it was before:  sensor.xx_x_x_xx_heating_target_temperature
outside_temp > in HA it was before:  sensor.xx_x_x_xx_outside_temperature

**Comment by denpamusic** [comment]
You're welcome!

Heating Target Temperature and Outside Temperature should already be available in hass for 850i as they are added for both "p" and "i"-series. If yours is disabled, try to enable it manually through the hass UI, by checking Enabled in Entity Status section as shown below and it should work.

![2022-12-02 (6)](https://user-images.githubusercontent.com/16575433/205258369-ac47cf2a-d548-42eb-898e-e7135a839f74.png)

**Comment by zASSAz** [comment]
For now I do not see any sensors, disabled or enabled , but I will try to delete and reconnect controllers after PyPlumIO will be fixed.
