### ISSUE TITLE
Total burned fuel

### ISSUE THREAD

**Issue by entmor** [denpamusic/PyPlumIO#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [X] documentation improvement
- [ ] other

### Feature description

Hi,

How can we get value something like "total_fuel_burned_kg"? i know only, that value is in regularData from ecomax[frame=8] and when i check regdata from ecomax, it is key 185
<img width="830" alt="Zrzut ekranu 2022-12-19 o 23 50 39" src="https://user-images.githubusercontent.com/32103221/208541901-769dcdc9-2d80-46ba-afe8-362f7d4d7e99.png">

btw. thanks you for your job. really nice lib

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

Interesting timing for you to ask this😁 I just started the work to solve chicken-egg problem with current regdata parser implementation. Currently it can be a major PITA to work with regdata, since `await get_value("regdata")` will return empty dictionary if schema is not yet available, which makes it impossible to reliable get regdata values without getting creative with callbacks.

However this will change in the next commit, which will probably be ready in a day or two.
Then you will be able to use following code to get your value:

```python
use asyncio
use pyplumio

async def main():
  async with pyplumio.open_serial_connection(device="/dev/ttyUSB0") as connection:
    ecomax = await connection.get_device("ecomax")
    regdata = await ecomax.get_value("regdata")
    print(regdata["total_fuel_burned"])

asyncio.run(main())
```

Also thank you for new info on the regdata schema. Now that you've tell me that 185 is a total burned fuel value, I've [added it](https://github.com/denpamusic/PyPlumIO/commit/4ba91abd5daeefbf22a01d71f6f4e207821fd47a) to the dictionary so it can be accessed by name.

Anyways, please wait a bit for the improvements to regdata parser and then you'll be able to use code above to get your value.

**Comment by denpamusic** [comment]
This is now done.
You can now use the following code to get the total fuel burned value:
```python
use asyncio
use pyplumio


async def main():
  """Print out total_fuel_burned value from the regdata once it'll become available
  and close the connection.
  """
  async with pyplumio.open_serial_connection(device="/dev/ttyUSB0") as connection:
    ecomax = await connection.get_device("ecomax")
    regdata = await ecomax.get_value("regdata")
    print(regdata["total_fuel_burned"])


asyncio.run(main())
```
Of course you can get any regdata value using this method or a whole regdata dictionary (e. g. ```print(await ecomax.get_value("regdata"))```)

**Comment by entmor** [comment]
Thx you 

i will test this solution today ;)

btw.  more regdata schema 

ecoMax920- soft kostrzewa - pellets boiler mini bio kostrzewa 

#30 - flame [%]
#31 - return_temp
#144 - fuel_stream [kg/h] 
#202 cycle_fedding [s]
#203 cycle_pause [s]

#177 - linear_actuator_position [int] - // 0 - stop |  2- start-moving? |  3-extending | 4 - retracting
i'm not sure about value 2, because i see this value only on start moving, like: 0,2,3,3,3,3,3,3,0 and 0,2,4,4,4,4,4,4,4
#180 - linear_actuator_position [float] 
#181 - work_at_100 [h] [int]
#182 - work_at_50 [h] [int]
#183 - work_at_30 [h] [int]
#184 - feeder_work [h] [int]
#186 - firingup_count [int]
#188 - linear_acuator_jammed [int]

#155 mixer_1_value [%] [int] - mixer position 0-100 %
#160 mixer_1_state [int] - 0-off/stop 1-closing 2-opening
#1031 - mixer_1_temp

#215 to_clean_ash  [kg] [float] 
#216 ash_pan_full [%] - int
example:
clean ash every 200kg burned fuel
value_216 = 25 [%] | value_215 = 150 [kg]
value_216 = 50 [%] | value_215 = 100 [kg]
value_216 = 90 [%] | value_215 = 20 [kg]

#1793 boiler_actu_power [kW] [float]


btw2.
in readme is: 
`connection.wait_until_done()`

instead
`await connection.wait_until_done()`

**Comment by denpamusic** [comment]
Thank you for the info!

Sadly after comparing your keys with the regdata from ecoMAX860 (under the spoiler below) it seems, that keys are different for different ecoMAX models. That means, that in order to properly convert from numerical keys to names, I'll need to implement selector based on the model.

This is a bit more involved than I like right now, since I'm also working on thermostats support, which is quite a large feature. So I'll probably finish with thermostats first and then return to the regdata. Hope you okay with waiting on names. (ofc you can still use numbers for now)

<details>
  <summary>ecoMAX860 regdata</summary>

  ```python
{
  '1792': 0
  '1538': False
  '1536': False
  '1537': False
  '2': False
  '1': False
  '1539': False
  '1543': False
  '1541': False
  '1542': False
  '1544': False
  '1545': False
  '1546': False
  '3': False
  '1540': False
  '1547': False
  '1548': False
  '1549': False
  '1550': False
  '1551': False
  '1552': False
  '4': False
  '1553': False
  '1554': False
  '1555': False
  '1556': False
  '1557': False
  '1558': False
  '5': False
  '8': 4095
  '11': 4095
  '12': 4095
  '13': 4095
  '14': 4095
  '10': 4095
  '9': 1183
  '7': 3848
  '15': 4095
  '18': 4095
  '6': 0
  '16': 0
  '17': 0
  '20': 0
  '21': 0
  '22': 0
  '23': 0
  '24': 0
  '25': 0
  '26': 0
  '1025': nan
  '1031': nan
  '1027': nan
  '28': nan
  '1030': nan
  '1026': nan
  '1024': 22.384185791015625
  '27': 0.0
  '1028': nan
  '1029': nan
  '1033': nan
  '1032': nan
  '30': nan
  '31': nan
  '1035': nan
  '1034': nan
  '32': nan
  '33': nan
  '34': nan
  '1281': 45
  '1287': 40
  '1283': 0
  '36': 0
  '1286': 0
  '1282': 0
  '1280': 41
  '35': 0
  '1284': 0
  '1285': 0
  '1289': 40
  '1288': 40
  '38': 0
  '39': 0
  '1291': 40
  '1290': 40
  '40': 0
  '41': 0
  '42': 0
  '44': 128
  '47': 0
  '48': 0
  '49': 0
  '50': 0
  '46': 0
  '45': 0
  '43': 0
  '51': 0
  '54': 0
  '52': 0
  '53': 0
  '56': 0
  '57': 0
  '58': 0
  '59': 0
  '60': 0
  '61': 0
  '62': 0
  '64': True
  '67': True
  '68': True
  '69': True
  '70': True
  '66': True
  '65': False
  '63': False
  '71': True
  '83': False
  '72': True
  '73': True
  '74': True
  '76': True
  '77': True
  '78': True
  '79': True
  '80': True
  '81': True
  '82': True
  '85': False
  '86': False
  '87': False
  '88': False
  '89': False
  '90': False
  '91': False
  '92': False
  '93': False
  '94': False
  '95': False
  '97': 0
  '98': 32
  '2048': 0
  '99': False
  '100': False
  '2049': 0
  '102': False
  '103': False
  '104': False
  '105': False
  '106': False
  '107': False
  '108': False
  '109': False
  '110': False
  '111': False
  '112': False
  '113': False
  '114': False
  '115': 64
  '116': 64
  '1794': 0
  '117': False
  '118': False
  '1798': False
  '119': False
  '120': False
  '121': True
  '122': True
  '123': True
  '124': True
  '125': True
  '126': True
  '127': True
  '128': 18
  '131': 75
  '132': 1
  '145': 0
  '146': 0
  '147': 0
  '148': 0
  '149': 0
  '150': 0
  '151': 0
  '152': 0
  '153': 0
  '154': 0
  '155': False
  '156': False
  '157': False
  '158': False
  '159': False
  '164': 2
  '165': 2
  '166': 1
  '160': 0
  '161': 0
  '162': 0.0
  '163': 0.0
  '1795': 0
  '96': 0
  '1793': 0.0
  '101': 0.0
  '170': 0
  '173': 0
  '176': 21
  '177': 9
  '178': 26
  '179': 13
  '181': 12
  '182': 29
  '171': 0.0
  '172': 0
  '174': 0
  '175': 0
  '183': '0.0.0.0'
  '184': '255.255.255.0'
  '185': '0.0.0.0'
  '186': 0
  '187': '0.0.0.0'
  '188': '255.255.255.0'
  '189': '0.0.0.0'
  '190': 1
  '191': 1
  '192': 100
  '193': 0
  '194': 0
  '195': ''
}
  ```

</details>

**Comment by denpamusic** [comment]
From v0.2.40 and upwards, regdata will be left as is (with numerical id). It is decided that decoding these ids falls outside the scope of the library, as it requires maintaining device database within the library.

Instead, such a library matching product ids to the regdata schema should probably be incorporated into the application.
